### ISSUE TITLE
The accuracy of the nasty resnext29 on CIFAR-100.

### ISSUE THREAD

**Issue by liuhao-lh** [VITA-Group/Nasty-Teacher#14]
Thanks for your excellent work!
When I use the nasty resnext29 as the teacher, the accuracy of the distilled resnet18, shufflenetV2, and resnext 29 is 73.83, 64.82, and 79.87 respectively. I did not change the json file. I wonder if some parameters need additional settings. Looking for your reply!

**Comment by HowieMa** [comment]
Thanks for your attention to our work, and I am really sorry for the late reply. 

You don't need to change the JSON file. 
The potential reason that your student networks perform better is that your trained "nasty teacher" is not so "nasty". 
Maybe you can check the accuracy and the final adversarial loss of your trained nasty ResNext-29. Here is a screenshot of my training log (you can also find this log in the attached link): 
![image](https://user-images.githubusercontent.com/25797674/168118776-5cb8a21e-0668-420d-b652-37f6642016d5.png)

Actually, I would say that your results can be reasonable.  In my experiments, I do find that training a nasty large network is not easy.

Here is the link to my trained nasty ResNext-29 on CIFAR-100 and training logs:  https://drive.google.com/file/d/1YtuyFclIfTZEKP0cMwXVEcMzQacyPMrW/view?usp=sharing

The experiments are conducted with Pytorch 1.4.0. I also retrain the resnet18 student with Pytorch 1.7.0 recently, and the results are similar. 

Maybe you can start from the provided nasty resnext29 to conduct your experiments. 
BTW, you may find our recent work helpful: https://github.com/HowieMa/stingy-teacher

If you have any questions, please let me know.

**Comment by liuhao-lh** [comment]
Thanks for your reply! I'll try again as you suggest.
